### ISSUE TITLE
Add source type in anticipation of some new sources being allowed in civic (e.g. ASCO abstracts, ClinVar, Clinical Trials)

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-server#264]
Currently CIViC only allows evidence that corresponds to peer reviewed publication indexed by PubMed.

There are at least two other categories of sources that have been proposed:
- Certain conference abstracts for conferences that publish abstracts online. Specifically, ASCO (http://meetinglibrary.asco.org/abstracts).
- ClinVar records.

There are two main motivations for allowing this:
- First, to capture the latest cutting edge evidence that hasn't yet been published but may already be influencing clinical decisions.  For example, early clinical trial findings are often presented at ASCO, sometimes years in advance of when the final publication comes out.
- Second, to capture high quality evidence that will never be published.  This is particularly relevant for predisposing germline variants.  In ClinVar, several labs may have submitted considerable evidence that a variant is benign, pathogenic, etc.  A ClinVar record may provide extensive rationale, documentation of their review procedures, agreement between multiple independent groups, etc.  But for many genes, the novelty of even solid understanding of the pathogenicity of a variant may not be publishable. Or the groups involved are not motivated to publish.  Variants that meet a certain high level of evidence in ClinVar may be suitable for CIViC even if they are never published.

This is a high level decision for CIViC.  Should the scope of CIViC be absolutely limited to peer-reviewed published evidence?  Or is CIViC a place to document evidence that has reached a threshold that is high enough to influence clinical practice (which is not exclusively represented by publication). 

From the CIViC meeting at NKI, it seems clear that for predisposing germline variants, a publication is not a hard requirement. Publications are considered but so is evidence published in resources like ClinVar.  If that evidence is strong enough, a predisposing variant interpretation will be returned to patients even when there is not a body of evidence in peer reviewed publications documented in PubMed.   

CIViC could be a place where this evidence could be discussed and the final interpretation debated by the community.  Feedback from the NKI meeting suggested that this could be a very valuable resource to the community and might allow us to engage a new (and large) user base of clinical pathologists.

**Comment by acoffman** [comment]
Adding an "evidence type" field is obviously pretty straightforward. I am curious though, how similar will these new evidence records be to our existing ones? 

Some fields will obviously be common between "types" (say the evidence statement, or the disease). Other fields (the obvious example being "source") will be pretty different depending on the evidence type.

Will they be distinct enough that we should introduce a different evidence record schema for each "type" or does it make more sense to tack on extra fields as needed and expand the notion of what constitutes a valid "source?"

**Comment by malachig** [comment]
For ClinVar we need a few examples to use as prototypes. Start with the idea that a ClinVar variant record could be analogous to a pubmed indexed publication. Could we treat it similarly and create one or more evidence records in CIViC?  How forced does that seem?  Does it fit the CIViC data model close enough for us to move forward with ClinVar as a new evidence source.

**Comment by kkrysiak** [comment]
During the NKI meeting, European clinical trials were mentioned to me. I know even less about accessing these as I do US trials but I was pointed to the following search page. This is probably worth digging into as well. It would be great if we could support these. https://www.clinicaltrialsregister.eu/ctr-search/search?query=olaparib

**Comment by kkrysiak** [comment]
We should also accept biorxiv.

**Comment by kkrysiak** [comment]
ASCO abstracts are now here: http://abstracts.asco.org/

**Comment by malachig** [comment]
Example ASCO API queries:

Presentation record example:
https://ml-couch.asco.org/records/148577

Abstract example:
https://ml-couch.asco.org/abstracts/148577

Then to get a list of all the unique IDs:
https://ml-couch.asco.org/abstracts/_all_docs 
https://ml-couch.asco.org/records/_all_docs

From these we could get all the author, title, citation info we need and create a link back to ASCO University any time we are discussing an abstract by creating a URL like this: 
https://meetinglibrary.asco.org/record/148577/abstract

**Comment by arpaddanos** [comment]
<img width="416" alt="abst1" src="https://user-images.githubusercontent.com/13948978/47880032-2eb05e00-ddf0-11e8-89f2-05f0be845a09.png">
<img width="418" alt="abst2" src="https://user-images.githubusercontent.com/13948978/47880033-2eb05e00-ddf0-11e8-98ab-092837f358c1.png">
<img width="417" alt="abst3" src="https://user-images.githubusercontent.com/13948978/47880034-2eb05e00-ddf0-11e8-8c44-4f4b831a38ea.png">
<img width="408" alt="abst4" src="https://user-images.githubusercontent.com/13948978/47880035-2eb05e00-ddf0-11e8-8144-90d89c282956.png">
<img width="412" alt="abst5" src="https://user-images.githubusercontent.com/13948978/47880036-2f48f480-ddf0-11e8-9afe-867607e4f6f1.png">
<img width="414" alt="abst6" src="https://user-images.githubusercontent.com/13948978/47880037-2f48f480-ddf0-11e8-8836-4b46e54d6b37.png">
<img width="415" alt="abst7" src="https://user-images.githubusercontent.com/13948978/47880038-2f48f480-ddf0-11e8-8726-a6ac8c547433.png">
<img width="430" alt="abst8" src="https://user-images.githubusercontent.com/13948978/47880039-2f48f480-ddf0-11e8-99de-39f0b2a0ce6e.png">

**Comment by susannasiebert** [comment]
Issue moved to [griffithlab/civic-client #976](https://github.com/griffithlab/civic-client/issues/976) via [**ZenHub**](https://www.zenhub.com/)

**Comment by arpaddanos** [comment]
Above are examples of how these are formatted in publications, and what people will be using to look for them

**Comment by susannasiebert** [comment]
Moved to the civic-client repo for better organization.
