### ISSUE TITLE
consider renaming variant origin labels to better harmonize with ACMG recommendations

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-server#288]
The ACMG guidelines argue against use of the terms "mutation" and polymorphism.  To be more consistent with these guidelines we could rename our `Variant Origin` values as follows:

Somatic mutation -> Somatic
Germline mutation -> Rare germline
Germline polymorphism -> Common germline
Unknown -> Unknown
N/A -> N/A

The help text should have some guidelines as to what constitute 'Common' and 'Rare'.

**Comment by susannasiebert** [comment]
Replaced by https://github.com/griffithlab/civic-client/issues/877
