### ISSUE TITLE
Display evidence grid under variant groups

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#348]
Currently there is a grid the shows the variants under a specific group but it would be helpful to also have an evidence grid that consists of all evidence under the variants within the variant group. It will require including the variant and gene names next to the evidence.

Related to https://github.com/griffithlab/civic-client/issues/800

**Comment by susannasiebert** [comment]
The server-side changes necessary for this feature have been merged in as part of PR https://github.com/griffithlab/civic-server#352. The new endpoint can be found at `api/variant_groups/:id/evidence_items`.
