### ISSUE TITLE
Add "Becoming an Editor" page to the help docs

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#355]

**Comment by kkrysiak** [comment]
Added this to the wrong side.

**Comment by obigriffith** [comment]
Description of what makes a good editor or domain expert:

Recommended qualifications:
Advanced degree in a relevant field

Minimum qualifications*:
Advanced graduate student
Publication record in relevant field
*Explain how and who will assess

Proven CIViC curation track record for promotion to editor:
At least 10 publication queue suggestions (Silver suggester badge) 
Submit at least 10 revisions (at least 5 to gene or variant summaries) (Silver reviser badge) 
Submit at least 10 new submitted evidence statements (5 must be accepted before promotion) (silver submitter badger)
Completed profile (Bronze biographer)
Review and understand CIViC help documentation

Application process:
An existing curator is nominated or self-nominated by contacting help@civicdb.org
Provide full name, affiliation, CV, contact info and CIViC profile id/name.

Approval process:
At least 2 existing editorial members and one administrator will review application materials, profile and CIViC curation track record, including review of submitted evidence, revisions, and publication. Application reviewers will agree to either promote, provisionally reject, or reject the application. A provisional rejection may be overcome if the curator demonstrates additional contributions in one of the categories above.
