### ISSUE TITLE
include array of assertions on variant requests

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-server#357]
To construct the assertions tags in the variant summary, the client will need an array of assertion objects. A count of evidence items would also be helpful, as I can show that in the tooltip to convey some additional info to users. The client could get this info from the variants/assertions endpoint but that would require another request, and as that endpoint includes the evidence items would be a somewhat heavy one.

Example variant object:
{
  id: number,
  clinvar entries: []
  coordinates: {}
  ...
  assertions: [
    id: number,
    description: string,    
    fda_approval: bool,
    nccn_guideline: string,
    evidence_item_count: number
  ]
  ...
}

**Comment by susannasiebert** [comment]
This endpoint already exists at `variants/:id/assertions`. It is paginated though, which I change easily. I will also need to add the evidence_item_count.

**Comment by susannasiebert** [comment]
The `evidence_item_count` has been added.

**Comment by jmcmichael** [comment]
Yeah, /variants/:id/assertions does have this, but I would prefer to keep the server requests to a minimum (that was one of the reasons the variant summary page took so long to load before). If I can get the assertions on the variant object (minus the evidence items), then I don't need to make the additional call.

**Comment by susannasiebert** [comment]
Ah ok, I understand now. I will add that.

**Comment by susannasiebert** [comment]
This has been added to the assertions PR. Let me know if it looks ok or if something needs to be changed/added.
