### ISSUE TITLE
Create an assertion for each evidence type.

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#362]

**Comment by kkrysiak** [comment]
Create an archetypal assertion of each of the 4 types (predictive, prognostic, diagnostic, and predisposing).

First three for a “famous” somatic variant and the last one for a”famous” germline variant.

**Comment by arpaddanos** [comment]
Spreadsheet for working on assertions:
https://docs.google.com/spreadsheets/d/1-mcGUHvHPgv79-hhRWjZq1vCY6w6HM0A1LFAmImhWEo/edit#gid=1090386551
