### ISSUE TITLE
Pull in data from AlleleRegistry

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#363]
When we can match, we should link to Allele Registry data
http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing

They allow for matching using HGVS or chr, start, stop, ref, var. I would recommend the latter. 

Ultimately we would want to pull in additional information but at first we would want to pull in the ID and link out to the allele registry. This would be a good collaborative effort with ClinGen. We can register alleles that don't match.

**Comment by kkrysiak** [comment]
The 13 is the version. You can see on ClinVar where the 14 is associated with GRCH38. https://www.ncbi.nlm.nih.gov/clinvar/variation/13961/

Unfortunately, these numbers are not universal. As in 13 != GRCH37. They iterate the version as updates are made. https://www.ncbi.nlm.nih.gov/clinvar/variation/12582/

**Comment by malachig** [comment]
To elaborate a bit further.

To be a valid HGVS expression, the sequence accession before the ":" should unambiguously refer to a **sequence** (e.g. DNA, RNA, protein).  The HGVS expressions we are using for MyVariant.info do not follow this rule.  "chr7" could refer to many sequences. "NC_000007" is a GenBank accession that refers to a submission record.  But to get to an unambiguous sequence you also need a version number.  "NC_000007.13" refers to a single unambiguous sequence.  It seems that these version numbers are incremented if the sequence changes, or when a new genome build is released.

For a particular version of the genome (e.g. build37), we can probably safely assume a simple mapping between the "chr7" style representations, and the "NC_000007.13".  Adam did this when he automatically created HGVS expressions at the genome level for all simple variants.  These were submitted in bulk to CIViC and then reviewed by editors.  We could follow the same approach here.

**Comment by malachig** [comment]
![accessions](https://user-images.githubusercontent.com/856728/32507064-0b2392d6-c3ac-11e7-9162-389c838be1b2.png)

Allele registry has a handy reference table for these accessions.

**Comment by susannasiebert** [comment]
Thank you. That's really helpful.

**Comment by obigriffith** [comment]
You can also find this through the NCBI assembly pages. Most current GRCh37 is at: https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.25/

most current GRCh38 is at: 
https://www.ncbi.nlm.nih.gov/assembly/1132361/

**Comment by kkrysiak** [comment]
Basic information is pulled in. I'm going to create a new issue for expanding that capability.
