### ISSUE TITLE
Add clinical trials ID to the advanced search page

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#380]
For the Advanced Search.
Evidence - clinical trials ID - is, is not, is empty
Source - clinical trials ID - is, is not, is empty

**Comment by kkrysiak** [comment]
Evidence may not be necessary given the new Gene/Evidence item status searches available in the advance Source search.

**Comment by susannasiebert** [comment]
NCT ID search for Sources has been implemented. Closing.
