### ISSUE TITLE
DOID link out is broken for some diseases

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#382]
It seems the leading zeros have been removed for the linkout to some of the disease ontology entities. For example, Myeloma should be 0070004 but is linking out to 70004. https://civic.genome.wustl.edu/events/genes/45/summary/variants/222/summary/evidence/522/summary

This is a report taken from a flagged entity.
```There is no such DOID:70004 (Myeloma). There is a DOID:0070004 (Myeloma Neoplasm) (note leading zeros); however, this does not appear in the drop down box. The link to the DO website doesn't point to a valid page.```

**Comment by susannasiebert** [comment]
This is actually a problem with the data in our database. Some DO IDs were imported without the leading 0s. Not sure why. @acoffman will need to fix that in the production database.

**Comment by susannasiebert** [comment]
There also doesn't seem to be any consistency as to whether or not leading 0s are required, e.g. 12603 `Acute Leukemia` is correct. This means that we will need to check on all DOIDs individually.

**Comment by kkrysiak** [comment]
Acute Leukemia doesn't have any leading zeros when you visit their page. There was something about later entries into their database where they started incorporating them.

**Comment by susannasiebert** [comment]
Right, but it's not clear which ones are supposed to have leading 0s and which ones do not. So we need to check every one of them to ensure that we have the correct id.

**Comment by kkrysiak** [comment]
It seems to be all the 5-digit ones beginning with 5 through 8 (and probably growing). I wonder if we can check that in the cancer slim file they provided us? I don't remember what format that is in.

**Comment by acoffman** [comment]
All invalid DOIDs have been resolved!
