### ISSUE TITLE
CIViC resource request for NEXUS ETH Zürich

### ISSUE THREAD

**Issue by vipints** [griffithlab/civic-server#389]
Hi CIViC team, 

My name is Vipin, working with NEXUS ETH Zürich. My role is to provide infrastructure support to the oncology team. As a part of precision medicine initiative here, we are responsible for the development of a Variant Interpretation Platform for Oncology. 

We would like to compare several existing infrastructures and find the optimal solution to fit our needs. I came across CIViC and thank you all for providing the service.  My question is, would you be willing to share the framework of CIViC with us, such that we can setup a dummy instance at NEXUS to gain insight with it? I saw the codebase available for local deployment. Let me know what you think and need. 

Regards, 
Vipin

**Comment by kkrysiak** [comment]
Vipin,

As you noted, our codebase is freely available. The software is under an MIT license for both the server (https://github.com/genome/civic-server/) and the client (https://github.com/genome/civic-client/). We do request that you please acknowledge CIViC, where appropriate. If you have specific questions or problems with your installation, let us know.

Members of the NEXUS team may also use the content of CIViC and create accounts on the live site freely which, ideally, would allow them to contribute back to the community content. This community knowledgebase therefore benefits all and reduces the curation burden for everyone. We understand that is not always the desired system for some groups.

The CIViC team would also be very curious how CIViC stacks up when compared to other infrastructures. Once you have tested it, any feedback you have would be greatly appreciated. This is an evolving resource and we are always looking to improve upon it. You can also contact the CIViC team at help@civicdb.org.

Thank you,
Kilannin Krysiak

**Comment by vipints** [comment]
Thank you for your comments @kkrysiak! 
I will start working on setting up a local instance of CIViC in NEXUS. The instance will be private and only have access to the NEXUS ETH members and I will acknowledge the CIViC team appropriately. I will update the progress on setting up the instance and our evaluation details with your team as well.
Best, 
Vipin

**Comment by malachig** [comment]
Good luck.  Let us know if you have problems.  Also if you would be willing to have NEXUS ETH listed on the about page as a user.  This list helps us to demonstrate the utilization of CIViC to our funders.

**Comment by vipints** [comment]
Sure @malachig. You can add us. We (ETH NEXUS Personalized Health Technologies) started working on building Swiss Variant Interpretation Platform for Oncology (SVIP-O) as a part of Swiss Personalized Health Network [`https://www.sphn.ch/en/projects.html`]. Thank you for the support.

**Comment by vipints** [comment]
Can you comment on the resource requirement for hosting the CIViC server and client at our site?
We are planning to have a machine instance with following resources: 

OS: Red Hat Enterprise Linux 7 (64-bit)
CPUs: 2
Memory: 8GB 
Disk space: 500GB

**Comment by malachig** [comment]
That amount of resources should be sufficient for testing I would imagine.  We routinely develop on Mac laptops and Ubuntu instances on the cloud.  In the past we have created an amazon AMI for development at hackathons.  I think the most recent one is now a bit out of date though.

**Comment by malachig** [comment]
You may find these docs helpful:
https://github.com/griffithlab/civic-server/wiki/Creating-the-CIViC-AMI
https://github.com/griffithlab/civic-server/wiki/Getting-Started-with-CIViC-Development-on-AWS

**Comment by vipints** [comment]
Thank you for the suggestion 👍

**Comment by vipints** [comment]
We have successfully installed a local instance of CIViC at our infrastructure. The whole process was quite smooth and thank you for the support! We will be starting the evaluation and will share you the details as well. Thanks again @malachig @kkrysiak

**Comment by obigriffith** [comment]
@vipints - This is really nice to hear. Thank you for providing this feedback. Please do stay in touch. Understanding how CIViC can help other groups/institutions is central to our goals/mission.

**Comment by vipints** [comment]
Hi @kkrysiak, @malachig, and @obigriffith, 
I spoke with my managers of Clinical Bioinformatics division at Swiss Institute of Bioinformatics and ETH Zürich regarding the functionalities of CIViC. They are interested to hear more from you guys. As a part of the Initiative here in Switzerland, we would like to have features which you already taken care in your project. Would it be possible to have a phone/zoom session (30-45 min) to discuss on how we will move further on this? We are happy to describe the details on our plans and it will be nice if you can also gives a brief summary of your work. I am sure that this will greatly help us in deciding on the infrastructure development. Hoping for a positive response from your side. 
Thanks in advance, Vipin

**Comment by obigriffith** [comment]
This is great news. We would be very happy to discuss with you. Would you like to suggest a series of dates/times that we can intersect against our calendars?

**Comment by vipints** [comment]
Thank you @obigriffith! 
Sure, does any of the following time frames work for you? 

15.03.2018, 09:00 - 11:00 CDT (15:00 - 17:00 CET) 
20.03.2018, 09:00 - 11:00 CDT (15:00 - 17:00 CET)
22.03.2018, 09:00 - 11:00 CDT (15:00 - 17:00 CET)
  
Please let me know whether one of these will work for you. (As I said before, we only requires 30-45 min)

**Comment by obigriffith** [comment]
Sorry for the slow response. Unfortunately all of these times are booked. Do you have any openings on Fri 23.03.2018? I'm open from 09:00-13:00 and 15:00-17:00 CDT.

**Comment by vipints** [comment]
That is alright. Unfortunately Fri 23.03.2018, we are out for a whole day meeting. How about any open slot on Mon 26.03.2018, 08:30 - 11:30 CDT? Thanks!

**Comment by obigriffith** [comment]
I think we could do 09:00 CDT.

**Comment by vipints** [comment]
Thanks!

**Comment by lisabang** [comment]
> That amount of resources should be sufficient for testing I would imagine. We routinely develop on Mac laptops and Ubuntu instances on the cloud. In the past we have created an amazon AMI for development at hackathons. I think the most recent one is now a bit out of date though.

Hi @kkrysiak, @malachig, and @obigriffith, working on a test implementation of CIVIC as well at the moment.   I was wondering if there might be an easy way to deploy the AMI to other regions besides us-west-2.  I can definitely go through the steps to make our own configuration (thank you for the clear documentation!) but if I did that it would be nice to keep that environment as an AMI available for the AWS region that we need.  It'd be great to get your thoughts.

**Comment by malachig** [comment]
@acoffman and @susannasiebert thoughts on sharing the base AWS AMI that CIViC is built on to different regions?
