### ISSUE TITLE
I broke flags

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#390]
I merged E384* and E384Ter in the admin interface, except I did this before I resolved the open flag on E384Ter. Now the Open Flag page is broken and there is an outstanding Open Flag on E384Ter.

The issue the flag caused was resolved by the merge, but I didn't resolve the flag prior to the merge.

**Comment by acoffman** [comment]
The immediate issue is fixed and I commented on the PR with the fix going forward. Closing this!
