### ISSUE TITLE
cors origin blocked for cbioportal.org

### ISSUE THREAD

**Issue by inodb** [griffithlab/civic-server#409]
Hey @susannasiebert !

Not sure what place would be best to post this. The CIVIC integration we have with cbioportal.org doesn't work anymore because of a new CORS policy:

```
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.cbioportal.org' is therefore not allowed access.
```

Would it be possible to change the CORS policy?

**Comment by susannasiebert** [comment]
I don't think anything about the CORS policy has changed but we moved to AWS earlier this week and in the process switched to using civicdb.org as our canonical URL. I wonder if that is causing this issue? What URL are you using to make your requests?

**Comment by inodb** [comment]
@susannasiebert ok thanks for quick reply, pointing to the new URL solves it indeed!

**Comment by susannasiebert** [comment]
Glad switching the URL worked for you. I will do some more digging to figure out why requests from civic.genome.wustl.edu get blocked. That is definitely not what we want.
