### ISSUE TITLE
endpoints returning multiple variants should include a field the client can use for sorting by amino acid or germline coord

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-server#41]
civic-client issue genome/civic-client#67 requires some kind of field that it can use to sort by amino acid or germline coordinate when displaying lists of variants.

**Comment by nspies13** [comment]
Right now, a quick fix for this is to throw everything that is not of the form "X123Y" at the top, then sort the amino acids by their coordinate. I can also add an integer into the spreadsheet so that you don't have to regex.

**Comment by jmcmichael** [comment]
Closing, see https://github.com/griffithlab/civic-client/issues/67 for further progress.
