### ISSUE TITLE
March data download 403 Forbidden

### ISSUE THREAD

**Issue by gaberudy** [griffithlab/civic-server#414]
Hey CIViC team,

We are trying to download the March snapshot and getting a 403 forbidden message from here:

https://civicdb.org/releases

The nighties and the Feb release are accessible.

Thanks, Gabe

**Comment by susannasiebert** [comment]
Hi Gabe,

This issue is now fixed. This seems to be systemic though in that the monthly data dumps are not created with the correct permissions. It will need take a bit more digging to find the cause if this but in the meantime you should be able to access the March files again.

- Susanna

**Comment by gaberudy** [comment]
Great, thanks. feel free to close!
