### ISSUE TITLE
civic_actionability_score doesn't always get set

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-server#424]
Some variants in the production database don't have a actionability score set (I had to backfill them manually). I suspect this happens for new variants. If that is the case, we just need to caluculate this field whenever a new variant gets created.

**Comment by ahwagner** [comment]
We would also want to update it whenever new evidence (or revision to evidence) is accepted for a variant.

**Comment by susannasiebert** [comment]
I believe that is already implemented. The update job currently gets called when the status of an evidence item changes and when an evidence item gets accepted.
