### ISSUE TITLE
Non-unix line endings

### ISSUE THREAD

**Issue by jakelever** [griffithlab/civic-server#425]
Hi, I found an evidence item that includes non-Unix line endings (0xD or \r) in the text description. When exported to the nightly files, this causes problems when loading the TSV into other tools (e.g. R).

The Evidence item is:
VHL / V170G / Von Hippel-Lindau Disease / Predisposing [EID5172]
https://civicdb.org/events/genes/58/summary/variants/1935/summary/evidence/5172

There's a pending edit to it and I can't figure out how to make an edit to a pending edit (if that's possible). But I guess a more permanent solution would be to strip them at some stage.

**Comment by obigriffith** [comment]
I reviewed and accepted the previous pending edit and proposed a new edit to (I think) remove the problem carriage return. If someone else could accept that I think this problem will go away.

**Comment by acoffman** [comment]
This has been resolved, closing!
