### ISSUE TITLE
Spelling error in disease name

### ISSUE THREAD

**Issue by gerthijs** [griffithlab/civic-server#438]
In the following evidence record 
https://civicdb.org/events/genes/41/summary/variants/838/summary/evidence/1935/summary#evidence
the disease name is defined as 
PTEN **Harmatoma** Tumor Syndrome
but this should be 
PTEN **Hamartoma** Tumor Syndrome as defined in DOID:0080191

**Comment by acoffman** [comment]
Thanks for pointing this out - it appears there was a manually entered version of this disease in addition to the canonical disease ontology entry. They have been merged and this is now corrected.
