### ISSUE TITLE
Mentions not appropriately linking to sources

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-server#475]
If you click on a Mention in the comments of a source, nothing happens.

Error from the developer tools.
<img width="873" alt="screen shot 2019-01-11 at 1 06 37 pm" src="https://user-images.githubusercontent.com/8527125/51054231-cde89300-15a1-11e9-8f53-ce13c425c522.png">

**Comment by kkrysiak** [comment]
I wonder if this is because it is a source suggestion and not an integrated source?

**Comment by acoffman** [comment]
This appears to be resolved in the current version.
