### ISSUE TITLE
Add PubMed ID to Assertion Get Data spreadsheet download

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-server#498]
Adding a column to the list of supporting evidence items spreadsheet that one downloads with the Pubmed ID supporting each EID which supports the assertion would be great.

**Comment by jmcmichael** [comment]
Opened a [civic-client issue](https://github.com/griffithlab/civic-client/issues/1084) for this. We've moved to creating all new tickets in the client repo.

**Comment by tmooney** [comment]
@jmcmichael You might be interested in the new "transfer issue" beta feature:
https://help.github.com/en/articles/transferring-an-issue-to-another-repository
