### ISSUE TITLE
No 01-june-2020 release available?

### ISSUE THREAD

**Issue by gaberudy** [griffithlab/civic-server#612]
Hi there, it looks like the June release did not get automatically created this month:

https://civicdb.org/releases

Any change in procedure so that we should not expect this, or was there maybe a hiccup in the automated process?

Thanks, Gabe

**Comment by acoffman** [comment]
Hi @gaberudy, 

Apologies for the issue, there was a problem with our automated process. We've addressed it and the june data dump should now be available. 


Thanks!
Adam
