### ISSUE TITLE
nightly-VariantSummaries: different number of columns? 

### ISSUE THREAD

**Issue by sigven** [griffithlab/civic-server#715]
Hi,

Thanks for a great resource. When trying to parse the `nightly-VariantSummaries` TSV file in R, i get a warning about some 9-10 records containing more columns than expected. I guess this might be caused by a missing value/formatting matter(?), it would either way be convenient to ensure that the number of columns are consistent for all records of this file.

Here is simple command that showcases it:

_(base) sigven$_ `awk 'BEGIN{FS="\t"}{print NF;}' nightly-VariantSummaries-20221118.tsv | sort | uniq -c`
`1612 29`
   `5 30`
   `2 31`
   `2 33`

Thanks in advance,

cheers,
Sigve

**Comment by acoffman** [comment]
Hi @sigven and @pdiakumis 

Thanks for bringing this to our attention, and apologies for the delayed response. CIViC development is taking place in the https://github.com/griffithlab/civic-v2/ repo these days, and so I initially missed this report.

We can confirm the issue you're seeing. Its the result of not properly joining the Assertion URL column in our export process. I have a fix ready that will go out in our next deploy which is scheduled for next week.
